### ISSUE TITLE
`listCurrent` handler throws for user without an organization

### ISSUE THREAD

**Issue by O4epegb** [calcom/cal.com#10377]
### Issue Summary

`listCurrent` api handler throws for user without an organization

https://github.com/calcom/cal.com/blob/6a163669413deeb32b15ff7653a05189cce99f8d/packages/trpc/server/routers/viewer/organizations/list.handler.ts#L15-L17

It's invoked in multiple places, for example, in `SettingsLayout` component:

https://github.com/calcom/cal.com/blob/2011a1bd3855a073118d14d83b8751b5ce688930/packages/features/settings/layouts/SettingsLayout.tsx#L201

I think it's not a big deal, but it just spams console with errors and makes dx a bit unpleasant 😄 

<img width="440" alt="Screen Shot 2023-07-25 at 19 00 27" src="https://github.com/calcom/cal.com/assets/12836237/fb33331f-e0e4-47b2-a2a7-b54cf0c9c87c">

### Steps to Reproduce

1. As user without organization go to `/settings/my-account/profile` for example
2. Check console

### Expected Results

No console error spam: api does not throw or query is disabled if there is no org or something else

----

It's my first issue here.
I would also like to fix it if someone more knowledgeable can tell me which solution is preferable in this case, disable the query or return `null` from the api for example? Or something else.

**Comment by keithwillcode** [comment]
This seems to have been fixed.

**Comment by O4epegb** [comment]
> This seems to have been fixed.

I don't think it is, it was just reworked a bit and renamed to `listOtherTeams`, but it still throws the same, just checked main branh and prod too

<img width="572" alt="Screenshot 2023-08-15 at 17 53 23" src="https://github.com/calcom/cal.com/assets/12836237/9cba9263-ef34-4fdc-a4bf-e2c20f0815dd">
