### ISSUE TITLE
[CAL-2266] Slots are open on wrong day in weekly view

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#10428]
### Issue Summary

Weekly view shows slots open on wrong day. 

<img width="785" alt="Screenshot 2023-07-27 at 16 12 51" src="https://github.com/calcom/cal.com/assets/30310907/42ea5c0b-7e1e-43a9-a452-f28caca8e78e">

<sub>[CAL-2266](https://linear.app/calcom/issue/CAL-2266/slots-are-open-on-wrong-day-in-weekly-view)</sub>

cc @sean-brydon

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
Hey! @CarinaWolli, I want to work on this issue.

**Comment by CarinaWolli** [comment]
@SOUMOJIT-CHAKRABORTY  Nice! Just link this issue in your PR when you are done 🙏

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
@CarinaWolli Thanks 😊

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
@CarinaWolli Can you tell me how can I see the weekly view?

**Comment by sean-brydon** [comment]
> @CarinaWolli Can you tell me how can I see the weekly view?

You will need to login as an ADMIN account (see see script) and enable it as a feature flag within the app. (settigns>admin>features)

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
Hey! I think the issue, **Showing wrong date** has been already resolved.

![Screenshot 2023-07-28 at 11 03 20 PM](https://github.com/calcom/cal.com/assets/88587765/0121d339-0ced-4f82-b3c2-4a6f6929bce1)

**Comment by CarinaWolli** [comment]
It's not yet fixed, but it's depending on the system timezone. I am in NY timezone and my weekly few is totally messed up and shows availabilities on wrong days.
