### ISSUE TITLE
All attempts to self-host and run locally following self-host instructions return error and container fails to start up.

### ISSUE THREAD

**Issue by toduyemi** [calcom/cal.com#13836]
=

### Issue Summary
Whenever I try to run commands `yarn dx` or `yarn dev`, I get this error (see pictures) and the container fails to start up. I've followed the self-host instructions to the letter. <running on macOS>

### Steps to Reproduce

1. Navigate to cal.com folder.
2. Run `yarn`
3. Create 32-character ssl keys and put them in correct fields in .env duplicated from .env.example.
4. Run yarn dx/yarn dev

### Actual Results

Container fails to spin up and web application fails to run locally.

### Expected Results

Ability to run app locally.

### Technical details

- Node.js version => v18.16.1

### Evidence
<img width="1273" alt="Screenshot_2024-02-21_at_9 22 42_PM" src="https://github.com/calcom/cal.com/assets/63010977/80a3e6dd-cdc1-4f22-8b88-74d0096d46fa">

<img width="1245" alt="Screenshot 2024-02-21 at 9 48 47 PM" src="https://github.com/calcom/cal.com/assets/63010977/d8326a83-8796-4a0a-8550-480a2463ac41">

**Comment by khsinat** [comment]
facing the same problem
will be solved soon?

**Comment by Udit-takkar** [comment]
fixed here https://github.com/calcom/cal.com/pull/13868

**Comment by toduyemi** [comment]
Requesting this issue be reopened. I am still experiencing the exact same errors thrown and problem. I am unable to run from `yarn dx`

**Comment by zomars** [comment]
@toduyemi the yarn dev error seems to be related to an invalid DATABASE_URL. Can you verify what value you have here? And on what port your DB container is running?
