### ISSUE TITLE
[CAL-3413] Booking frequency limit doesn't allow a scheduled booking to be rescheduled in the same week, even though it doesn't surpass booking limit.

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14584]
Step 1: Create booking frequency (e.g 3 bookings a week)
Step 2: Book 3 meetings
Step 3: Reschedule one of them for any time within the same week. 
Step 4: You are not allowed to reschedule even tho you are within the limits for the week

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3413](https://linear.app/calcom/issue/CAL-3413/booking-frequency-limit-doesnt-allow-a-scheduled-booking-to-be)</sub>

**Comment by Amit91848** [comment]
Couldn't replicate, this was fixed in #13867   #13870 


https://github.com/calcom/cal.com/assets/74371312/4a7f07a3-f219-4720-b924-c8c22a35de61

**Comment by CarinaWolli** [comment]
I can still reproduce this issue, I tested: 
- booking limit: 1 booking per year 
- create one booking
- reschedule booking
- no slots open for this year
