### ISSUE TITLE
[CAL-3965] Lark calendar does not check for conflict.

### ISSUE THREAD

**Issue by joseuo94** [calcom/cal.com#15528]
A customer reached out to inform Lark Calendar is connected but not working properly it allows to book an already taken slot.

I installed the app and also toggled check for conflict On.
But it allows me to book that slot.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5037165b-c884-449e-aafe-8c1b124c8d59/13c23ab9-8813-4336-8e36-db98458612fc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy81MDM3MTY1Yi1jODg0LTQ0OWUtYWFmZS04YzFiMTI0YzhkNTkvMTNjMjNhYjktODgxMy00MzM2LThlMzYtZGI5ODQ1ODYxMmZjIiwiaWF0IjoxNzE4OTgzNTgyLCJleHAiOjE3NTA1MTk1ODJ9.KxHMfSlgtalni3Yj5Io_XIZXHvmRIhNgRU_Cd5vgz9I)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a2d8ba16-495a-4535-b63d-2874003a8bf8/7826287a-83ff-454b-a80c-82f23ac53d09?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hMmQ4YmExNi00OTVhLTQ1MzUtYjYzZC0yODc0MDAzYThiZjgvNzgyNjI4N2EtODNmZi00NTRiLWE4MGMtODJmMjNhYzUzZDA5IiwiaWF0IjoxNzE4OTgzNTgyLCJleHAiOjE3NTA1MTk1ODJ9.fjijhqzzyKs5yM6jnrlqIxmfkYn-I0iq5WQ8teY3hmI)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/26b4856f-0694-4518-abab-3103f4bae8bd/48a8f1e7-ae2d-4464-8f30-0fce01398c71?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8yNmI0ODU2Zi0wNjk0LTQ1MTgtYWJhYi0zMTAzZjRiYWU4YmQvNDhhOGYxZTctYWUyZC00NDY0LThmMzAtMGZjZTAxMzk4YzcxIiwiaWF0IjoxNzE4OTgzNTgyLCJleHAiOjE3NTA1MTk1ODJ9.MIL8nyWugr9-5VhIFfdM5X9n3ObAddmjC7VWYhSFcJs)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/361adbfa-5a38-45e2-a914-6d43e437ab91/8c700c4d-7093-4e50-8f9a-85fd375e329d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zNjFhZGJmYS01YTM4LTQ1ZTItYTkxNC02ZDQzZTQzN2FiOTEvOGM3MDBjNGQtNzA5My00ZTUwLThmOWEtODVmZDM3NWUzMjlkIiwiaWF0IjoxNzE4OTgzNTgyLCJleHAiOjE3NTA1MTk1ODJ9.LAb7TmESWzTTrNchGjEwn889wu5_tXcmlmzdplGyMYM)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3965](https://linear.app/calcom/issue/CAL-3965/lark-calendar-does-not-check-for-conflict)</sub>

**Comment by Sahil-kachhap** [comment]
Hello @joseuo94, I am new to this codebase. Can I work on this issue. Any suggestion you could share to get started on this issue

**Comment by Vasant79** [comment]
@joseuo94 I tried to recreate it, did not get any issue regarding conflict booking probably it is already fixed

**Comment by sdoh55** [comment]
Hi, this still isn't working for me. None of the events created on Lark calendar show up in the troubleshooting page of cal.com except for the actual event created thru cal.com (titled "Beta Tester Feedback"). It also shows up twice for some reason, but it does block that time off from further bookings.

Lark calendar
![image](https://github.com/user-attachments/assets/025f2a93-fe66-4794-96f5-7712a1c9d996)

Troubleshooting page
![image](https://github.com/user-attachments/assets/4fa7a33e-4187-45b0-9f96-aa655640b2dd)

I tried looking thru the Lark API docs and was not able to find the "/calendar/v4/freebusy/batch_get" API used for [getAvailability](https://github.com/calcom/cal.com/blob/main/packages/app-store/larkcalendar/lib/CalendarService.ts#L295). Where is that coming from?

I also tried to call that API with a custom app to test, but it says I'm missing scope for "calendar:calendar.freebusy:readonly" that I don't even see an option to request the permission for. I'd love to help fix this issue if someone can point me in the right direction.
