### ISSUE TITLE
[CAL-4743] Day of week on confirmations

### ISSUE THREAD

**Issue by ktneely1230** [calcom/cal.com#17192]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When clients receive a confirmation email, the day of the week is in Spanish, ie instead of Sat. for Saturday, it reads sab for Sabado.

### Steps to Reproduce

1. When a client books an appointment
2. The confirmation email includes the wrong language for the day of the week (everything else on the confirmation page is in English)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect it to use the dominant language (English) of the associated time zone (America/Los Angeles PST)

- What's happening right now that is different from what is expected

clients are seeing the confirmed email with Sab instead of Sat.

- This is an ideal result that the system should get after the tests are performed

Days of the week in English for America/Los Angeles timezone

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.
![cal photo](https://github.com/user-attachments/assets/aa490ed1-264d-4007-9dc2-a8dad6850d50)

<sub>[CAL-4743](https://linear.app/calcom/issue/CAL-4743/day-of-week-on-confirmations)</sub>

**Comment by khushalmajoka** [comment]
Hi @ktneely1230, can u clarify more clearly the steps to reproduce.

**Comment by khushalmajoka** [comment]
This is from the mail i received, pls check it once again and tell the steps to reproduce so that I can test it.

![image](https://github.com/user-attachments/assets/192ba8d2-4d0c-4b9a-b77a-a3b2118b6493)

**Comment by ktneely1230** [comment]
After doing some additional testing, it looks like the confirmation is correct, but the reminder email shows the wrong language for the day of the week.

**Comment by khushalmajoka** [comment]
Yes rightly said, working on it.

**Comment by khushalmajoka** [comment]
Hi @ktneely1230 ,

Are we sending reminder emails only in English for every locale? if so then that means I should set the locale of this too in English only, right?

**Comment by ktneely1230** [comment]
Yes that is correct.Sent from my iPhoneOn Oct 23, 2024, at 1:22 AM, Khushal Majoka ***@***.***> wrote:﻿
Hi @ktneely1230 ,
Are we sending reminder emails only in English for every locale? if so then that means I should set the locale of this too in English only, right?

**Comment by khushalmajoka** [comment]
Hi @ktneely1230 , I have fixed the issue, can u please check.

**Comment by nikwen** [comment]
I'm still seeing this issue in production on Cal.com.

![Screenshot 1](https://github.com/user-attachments/assets/91034fab-aea7-4e1e-8828-6bc474d12f48)

Another screenshot:

![Screenshot 2](https://github.com/user-attachments/assets/22de1a98-79c4-4a8f-9031-f67fe83e2b3a)

I was using the most recent Firefox in incognito mode, with the system and browser language set to English (US) and the system clock set to the `America/New_York` time zone.

It doesn't happen every time I book an event, but it happens often enough.
