### ISSUE TITLE
[CAL-4907] Close.com integration not working

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#18217]
a customer reported but i havent verified this yet.

<sub>[CAL-4907](https://linear.app/calcom/issue/CAL-4907/closecom-integration-not-working)</sub>

**Comment by asadath1395** [comment]
@emrysal Seems like `CLOSECOM_CLIENT_ID` and `CLOSECOM_CLIENT_SECRET` has not been added in `.env` file, could you please check this?

**Comment by lotfi-mj** [comment]
Hello, no update since the 20th dec? When is this coming back up? Issue is still there. Thanks

**Comment by lotfi-mj** [comment]
> a customer reported but i havent verified this yet.
> 
> [CAL-4907](https://linear.app/calcom/issue/CAL-4907/closecom-integration-not-working)

 Any update on fixing this? Issue still remains..... Can't connect to my close CRM.

**Comment by Praashh** [comment]
> > a customer reported but i havent verified this yet.
> > [CAL-4907](https://linear.app/calcom/issue/CAL-4907/closecom-integration-not-working)
> 
> Any update on fixing this? Issue still remains..... Can't connect to my close CRM.

it was an env variable issue, it should be fixed soon

**Comment by PeerRich** [comment]
fixed this!

**Comment by lotfi-mj** [comment]
<img width="544" alt="Image" src="https://github.com/user-attachments/assets/62eea632-d508-4292-ad09-a713336014d0" />

Still showing an error, how to fix this issue? is it something else?

**Comment by lotfi-mj** [comment]
[image: image.png]

How to fix this problem?
