### ISSUE TITLE
Past call bookings shouldn’t have the cancel event option.

### ISSUE THREAD

**Issue by mursaleen-nisar** [calcom/cal.com#22370]
## Proposal

Currently, users are able to see and use the "Cancel Event" option even for past call bookings. This behavior is misleading, as canceling an event that has already occurred has no practical effect and may lead to confusion or misuse.

### Suggested Solution

- Disable or hide the "Cancel Event" button for any call bookings that are in the past (i.e., where the event end time is earlier than the current time).
- Ensure the UI reflects this change consistently across all relevant views (e.g., booking details page, event list, etc.).
- Optionally, provide a tooltip or status indicator to explain that past events cannot be cancelled.

### Benefits

- Improves user experience by preventing actions that are no longer valid.
- Reduces potential for errors or misunderstandings around event management.
- Maintains a clearer distinction between past and upcoming bookings in terms of available actions.

### Notes

If cancellation of past events is currently being logged or triggering backend workflows, ensure this logic is updated accordingly to prevent unnecessary processing.

**Comment by larson-carter** [comment]
Hmm should we disable the cancel button or should we replace it with a button/tooltip stating that the booking is from the past?

What is best for the user perspective?

**Comment by mursaleen-nisar** [comment]
I think it should be completely removed, it will not be confusing for this user.

**Comment by larson-carter** [comment]
@mursaleen-nisar - Thanks for the feedback. Tonight, I'll get my codebase/dev env setup again and I will implement it.

This seems super straight forward, however if you want to attach any extra docs, screenshots, etc. That would be nice so this can be done asynchronously. However, I don't believe it is necessary for such a small task.

**Comment by larson-carter** [comment]
@mursaleen-nisar - So sorry for the delay. I got covered up over the weekend and spent some time learning the codebase and such.

I did make a [PR](https://github.com/calcom/cal.com/pull/22482) hopefully I did things correctly and people can chime in and test it out.

**Comment by mursaleen-nisar** [comment]
No worries at all, @larson-carter — totally understand! Appreciate you taking the time to dig into the codebase and putting together the PR.

**Comment by Anshumancanrock** [comment]
@mursaleen-nisar  Hey Sir! I already created a PR to remove the delete button for past bookings. Please take a look #22510 and let me know if you'd like any changes or improvements. Appreciate your time !

**Comment by larson-carter** [comment]
@Anshumancanrock - Your PR seems to be **oddly** identical to my implementation and albeit chronologically _after_ my PR #22482. 

Guess this is another case of OSS going south...

**Comment by Anshumancanrock** [comment]
@larson-carter Bro, Are you serious right now?

You literally made a 2-line frontend tweak without even touching the backend where the actual fix was needed.
I pushed the full working fix both frontend and backend yesterday, and now you come around, blatantly copy my code, push it under your PR, and then have the audacity to accuse me?

You’re the one trying to hijack my work, not the other way around. Don’t mask your own actions with OSS guilt-tripping. If anything’s going south here, it’s your attempt at sneaking in someone else’s effort as your own.

You do realize all of this is traceable, right?

**Comment by larson-carter** [comment]
@Anshumancanrock 

>  You literally made a 2-line frontend tweak without even touching the backend where the actual fix was needed.
I pushed the full working fix both frontend and backend yesterday, and now you come around, blatantly copy my code, push it under your PR, and then have the audacity to accuse me?
- Not going to play the pointing finger game. However at Jul 14, 2025 11:28AM CDT i left my final comment regarding the backend fix. Your commits didn't go live till Jul 14, 2025 9:45PM CDT

> You’re the one trying to hijack my work, not the other way around. Don’t mask your own actions with OSS guilt-tripping. If anything’s going south here, it’s your attempt at sneaking in someone else’s effort as your own.
- Timestamps are showing otherwise?

> You do realize all of this is traceable, right?
- Yes, and I am showing the traceability factor here.

Regardless, find it odd how over 10 hours later, my commits and my comment get pushed to your code and opened into a PR. Once again, anyone agrees it is a minor fix overall.. I just stated that it was odd.

**Comment by Anshumancanrock** [comment]
@larson-carter I didn’t even see your comment and let’s be real, it’s still not a full fix.
Your PR's unit tests are still failing, while mine already passed yesterday.

<img width="1917" height="781" alt="Image" src="https://github.com/user-attachments/assets/a8be5cb0-5973-4774-b1d5-f8eb0627d3ac" />

And you’re here fighting with me that you did't copy my code.
That’s some next-level irony.

**Comment by Anshumancanrock** [comment]
@mursaleen-nisar Please look into the matter sir. Thank you !
