### ISSUE TITLE
Issue in latest pull related to locales

### ISSUE THREAD

**Issue by shaun-ak** [calcom/cal.com#22460]
### Issue Summary

After taking latest pull and running `yarn dev`, I get these warnings in console and also automatically there are 44 file changes all related to locales.

This is happening repeatedly.

### Steps to Reproduce

1. Take latest pull
2. do `yarn` and then do db-migrate
3. run `yarn dev`

### Evidence

<img width="837" height="786" alt="Image" src="https://github.com/user-attachments/assets/d0c024a1-d82b-428d-a871-b7625438524d" />

<img width="837" height="786" alt="Image" src="https://github.com/user-attachments/assets/aced4f09-adfd-4cf1-8b2c-3e6844f467a7" />

**Comment by yogendrarana** [comment]
Also the translation is not working

<img width="1922" height="990" alt="Image" src="https://github.com/user-attachments/assets/c27c7ec9-1601-4acd-b785-9ee387297454" />

**Comment by sahitya-chandra** [comment]
This issue is fixed now and it can be closed.

**Comment by shaun-ak** [comment]
I can still see the warnings in console regarding duplicate keys, but the auto generated file changes are not happening any more.

Maybe we can close this issue?
