### ISSUE TITLE
James sinka bug - cal.com/james

### ISSUE THREAD

**Issue by JxSinka** [calcom/cal.com#2615]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. my working hours availability says saved (Tues and Thurs)
2. when I set/config my cal.com bookings I set it to my working hours
3. when I check cal.com/james - it doesnt show just Tue Thur as is my availability
4. help
<img width="1401" alt="Screen Shot 2022-04-25 at 8 26 19 PM" src="https://user-images.githubusercontent.com/56697925/165291825-8b517c6a-a0b6-4d7c-b76c-d6094c0efed5.png">
<img width="916" alt="image" src="https://user-images.githubusercontent.com/56697925/165291943-135678dd-4d87-4094-b4cc-e999e6598579.png">

5. 
6. 
7. 
8. for example) Went to ...
9. Clicked on...
10. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by JxSinka** [comment]
hi - we still have an issue

my [cal.com](http://cal.com/) timeslot doesnt sync with my [jamessinka@gmail.com](mailto:jamessinka@gmail.com) calendar - can u pls debug?

![image](https://user-images.githubusercontent.com/56697925/165518422-55fbd1c6-92ff-40f4-a1df-8f8c2293ee78.png)

**Comment by emrysal** [comment]
Could you disconnect and reconnect your calendar? Looking around at your availability it seems like it's disconnected.

**Comment by JxSinka** [comment]
on the troubleshoot function it works - https://app.cal.com/availability/troubleshoot

but on the live cal.com/james - it is unsynced

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/56697925/165540851-6f203db4-7bd4-4f7d-a814-ef8f1cfda153.png">

**Comment by emrysal** [comment]
How is your calendar setup shown at https://app.cal.com/apps/installed ?

**Comment by JxSinka** [comment]
turns out the entire cal.com/james is bugged - so I created a new
cal.com/jamessinka and it works perfectly. can you please debug my old name
so I can have cal.com/james back?
www.jamessinka.com
Twitter <http://twitter.com/jamessinka>
NYT <https://www.nytimes.com/2019/11/07/style/dopamine-fasting.html>
LinkedIn <https://www.linkedin.com/in/jamessinka/>

**Comment by agustif** [comment]
Hey James, do you have any settings or history of bookings you want to save from your old account?

I was thinking if debugging this is hard. Maybe an easy solution is to swap usernames in the database for james <-> jamessinka. So you get the correct settings in your old username?

Let me know if that solution works for ya, should be the easiest way to solve your issue

**Comment by PeerRich** [comment]
this has been resolved @JxSinka

**Comment by JxSinka** [comment]
hi - we still have an issue

my cal.com timeslot doesnt sync with my ***@***.*** calendar - can
u pls debug?

[image: image.png]
www.jamessinka.com
Twitter <http://twitter.com/jamessinka>
NYT <https://www.nytimes.com/2019/11/07/style/dopamine-fasting.html>
LinkedIn <https://www.linkedin.com/in/jamessinka/>
