### ISSUE TITLE
Getting Message "A Meeting URL will be created once the event is confirmed" instead of Zoom-Link

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#3115]
### Issue Summary

When using Zoom as location the notification email says, that a meeting URL will be created once the event is confirmed, even though the confirmation mode is not used. The link is generated in zoom, but is missing in emails and calendar entry.

### Steps to Reproduce

1. Create an event via Zoom without activating confirmation mode
2. Book an event via Zoom
3. Zoom-Link is missing in confirmation mail, instead there's a note saying "A Meeting URL will be created once the event is confirmed". Calendar entry is also missing the zoom-link.

### Technical details

- Browser version: Firefox 101.0.1
- Node.js version: v14.19.3
- cal.com selfhosted (1.7.1)

**Comment by emrysal** [comment]
This is fixed in main (Due to go live in 1.7.2)

**Comment by bhopmann** [comment]
Thank you, I've tried main, but it seems that the Zoom-Link is still missing:

<img width="180" alt="Bildschirmfoto 2022-06-20 um 18 53 08" src="https://user-images.githubusercontent.com/2770597/174648487-0ccbcf23-06bb-412a-b94f-1a3575efa515.png">

**Comment by zomars** [comment]
I know @alannnc did some adjustments recently to the Zoom schema validator it should be a quick fix.
