### ISSUE TITLE
[CAL-1684] wrong meeting organizer used with multiple Google accounts

### ISSUE THREAD

**Issue by aspiers** [calcom/cal.com#3643]
### Issue Summary

I have multiple Google accounts connected (one personal, and two for work):

![image](https://user-images.githubusercontent.com/100738/182369620-3c8d1c6f-ad43-42c8-ad80-b3571bd62d00.png)

and some event types which are configured to book events onto one of the secondary (i.e. non-default) Google calendars which I use for work:

![image](https://user-images.githubusercontent.com/100738/182369944-83150f54-edb4-4d84-b478-71a69b7b2e60.png)

When bookings are made with these event types, they appear correctly on the secondary calendar, but with my cal.com account's main email address as the organizer:

![image](https://user-images.githubusercontent.com/100738/182370671-4c7b35f5-3ce5-4abc-bc2d-775d66dfb63b.png)

### Steps to Reproduce

1. Connect multiple Google accounts (actually this might be reproducible even with one Google account, if that account's email address doesn't match the cal.com account's email address?)
2. Create an event type which books onto a specific Google calendar, and auto-creates a Google Meet link.
3. Get someone to book an event using this event type.
4. Observe that the event organizer is listed as my cal.com account's main email address, rather than my Google account's email address.
5. Observe that despite this, joining the Google Meet from the same work account which owns the calendar it's booked onto results in me correctly being assigned as meeting host.

### Expected results

The calendar event should list my Google work account's email address as the organizer, and not mention the personal email address which my cal.com account is registered with.

## Related issues

I found other issues probably related to this:

- #8444
- #11734 
- #6751

<sub>[CAL-1684](https://linear.app/calcom/issue/CAL-1684/wrong-meeting-organizer-used-with-multiple-google-accounts)</sub>

**Comment by aspiers** [comment]
BTW there is another undesirable consequence of this issue: emails about this booking will go to the cal.com account's main email address rather than to the address of the Google account on whose calendar the event is booked.  So effectively I then get emails about a work meeting going to my personal email account rather than to my work account.

**Comment by PeerRich** [comment]
> BTW there is another undesirable consequence of this issue: emails about this booking will go to the cal.com account's main email address rather than to the address of the Google account on whose calendar the event is booked. So effectively I then get emails about a work meeting going to my personal email account rather than to my work account.

that is very true and would need a bit of refactor to actually send it to the email of your calendar.

not everyone wants that by default.

will think about this

**Comment by aspiers** [comment]
Thanks for the response!  Interesting to hear that not everyone would want the notifications going to the email account associated with the calendar.  Of course you know much better than me how much coding/refactoring would be required on the backend to make this configurable.

From a UI perspective, I guess this could be solved simply by adding a new dropdown (e.g. just below the "Create events on:" dropdown) called "Host email address:" or similar.  Then users could choose between their main cal.com email and the email associated with the calendar in question (or indeed any email address belonging to the user which cal.com knows about).

**Comment by PeerRich** [comment]
lemme run this by the team!

**Comment by vtrikoupis** [comment]
Is there an update on this?

**Comment by PeerRich** [comment]
escalated priority

**Comment by trevor-s8** [comment]
Another vote for this. Trying to mix work and personal scheduling under the same account is currently impossible due to this limitation

**Comment by Jaibles** [comment]
We have designs for this here: https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/3.-Cal---New-Features?type=design&node-id=1021%3A104990&t=fwtZI0VSbiQxGBcR-1

**Comment by pheuberger** [comment]
I have the same problem. Upvoted!

**Comment by aspiers** [comment]
Any progress on this? This is actually a huge problem for me, to the point that I'm considering stopping using cal.com because it's simply unusable:

- "Awaiting Approval" email notifications about bookings are being incorrectly sent to my personal email account instead of my work account.
- **This leads me to missing them during working hours, so then I'm slow to respond which makes me look unprofessional to my business partners!**
- It spams my personal inbox with work emails.
- It exposes two of my personal addresses to work contacts, which can be a serious privacy concern.

**Comment by aspiers** [comment]
I found other issues probably related to this:

- #8444
- #11734 
- #6751

**Comment by aspiers** [comment]
Created a Discord topic in the hope that it will aid making progress on these: https://discord.com/channels/1125390093386010654/1161022259935322133/1161022259935322133

**Comment by keithwillcode** [comment]
Going to bump this in priority

**Comment by asadath1395** [comment]
@keithwillcode I would like to work on this, can you assign this to me? Thanks

@ciaranha Shouldn't we have a way to resend the emails for newly added secondary emails? Didn't see that in design

**Comment by zomars** [comment]
@PeerRich does this still need approval? I saw @Udit-takkar is working on this.

**Comment by foxted** [comment]
When choosing a secondary calendar as the organizer, the confirmation page after booking a meeting also display the main account email, as opposed to the email attached to the secondary calendar.

**Comment by Udit-takkar** [comment]
@foxted yeah i fixed all this on my PR. i am just testing for any edge cases

**Comment by jjeremycai** [comment]
Stoked for this to go live!

**Comment by ciaranha** [comment]
@Udit-takkar this still shows the email of my account on the event confirmation... I would expect to see the "Add to calendar" here on the booking confirmation


![CleanShot 2024-02-15 at 15 35 01@2x](https://github.com/calcom/cal.com/assets/4536123/974eecfd-4b0c-4d93-80c8-e72aa9b413b9)
