### ISSUE TITLE
grey text on black button when adding another Google Calendar app

### ISSUE THREAD

**Issue by aspiers** [calcom/cal.com#3663]
The `Add another` button at https://app.cal.com/apps/google-calendar has grey on black text and is almost unreadable:

![image](https://user-images.githubusercontent.com/100738/182484993-abb9cc6c-73be-4a53-aa65-bc1f40ecf938.png)

The contrast between foreground and background colours obviously needs to be much bigger.

### Technical details

- Chrome version 102.0.5005.115 (Official Build) (64-bit)

**Comment by matheusmuniz03** [comment]
Hey @aspiers, here is normal, did you update cal.com?
![Captura de tela de 2022-08-03 09-06-59](https://user-images.githubusercontent.com/87545749/182604015-b70f29e1-6166-40b6-9684-e6b779d240d6.png)

**Comment by PeerRich** [comment]
@aspiers did change your theme color? https://app.cal.com/settings/profile maybe that's why. @alishaz-polymath ?

**Comment by aspiers** [comment]
Thanks for quick reply! I don't remember changing it but I'll check!

**Comment by alishaz-polymath** [comment]
Technically, the text and bg should have a contrasting color if everything in brand color is working as expected. Unless there's a missing class for text color in this specific button(which I doubt), it's very very strange indeed. Worse is, I can't recreate it.

**Comment by alishaz-polymath** [comment]
@aspiers can we impersonate you to take a look at this?

**Comment by aspiers** [comment]
Sure!

**Comment by alishaz-polymath** [comment]
Okay, I've identified why this is happening.
https://github.com/calcom/cal.com/blob/main/apps/storybook/tailwind.config.js#L10-L134
the variable `--brand-color` is rendered useless here as it isn't mapped to any class and the class brand is associated with default colors instead. For this reason, the brand color is being taken as default even when the users are changing them, while the text brand color is taken as the contrast to their actual brand color (since the calculation for both happen in the same place).
@sean-brydon Can you please take a look here, since you're working on storybook the most. 🙏

**Comment by aspiers** [comment]
I see something very similar in the advanced settings of event types; is this the same bug?

![image](https://user-images.githubusercontent.com/100738/182658168-5360acf3-5ec2-4690-8622-a599774ed7da.png)

**Comment by PeerRich** [comment]
@leog can you look into this, too?

**Comment by aspiers** [comment]
Also the `Update` button:

![image](https://user-images.githubusercontent.com/100738/182662430-15c8551f-3d32-493a-bde1-22240136d4f2.png)

**Comment by leog** [comment]
Same issue @aspiers @PeerRich. Will make a hotfix to push to PROD to have it fixed ASAP. Thank you very much @aspiers for bringing this to our attention, really appreciated!

**Comment by leog** [comment]
It should be fixed now in PROD @aspiers. Thanks again 💪

**Comment by aspiers** [comment]
Thanks for the incredibly quick action @leog! I can confirm that the single buttons are now fixed but some dropdowns such as the `Create events on:` one screenshotted above still have the problem.

**Comment by aspiers** [comment]
I still see this, e.g.

![image](https://user-images.githubusercontent.com/100738/219520623-f13d91c5-0906-420d-9794-a454516391c9.png)

**Comment by aspiers** [comment]
Filed #7164 to track.
