### ISSUE TITLE
[CAL-149] Zoom causes a JSON error after a while

### ISSUE THREAD

**Issue by MinhazI** [calcom/cal.com#4793]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When someone tries to book a meeting through my Cal.com links, it doesn't work as expected. The meeting doesn't get added to my Google calendar and throws the error: `Could not book the meeting. Unexpected end of JSON input` but the meeting is there on Cal.com's app meeting section where I can see all meetings that are booked via Cal.com

### Steps to Reproduce

1. Went to https://cal.com/win-authority/discovery-call
2. Selected the date and filled in all the details
3. Then the error `Could not book the meeting. Unexpected end of JSON input` shows up

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
I consider this a bug because the user cannot book meetings with me and it doesn't appear on my Google calendar. Instead, it should prompt the user with a success message and he/she should receive an email with the meeting info I should receive an email as well along with the meeting being in my Google calendar.

### Technical details

- 106.0.5249.91 (Official Build) (64-bit) (cohort: Rampup_106) 
- The following error is shown on Chrome's console:
`Failed to load resource: the server responded with a status of 500 ()`
`_app-7cb944f9e5a16ad9.js:1 SyntaxError: Unexpected end of JSON input
    at 6470-ceccfe201fab6ebb.js:1:22082
    at l (main-e5b513407ef9dae7.js:1:109170)
    at Generator._invoke (main-e5b513407ef9dae7.js:1:108958)
    at forEach.e.<computed> [as next] (main-e5b513407ef9dae7.js:1:109593)
    at s (1213-6f9fd55cdf262f97.js:1:3100)
    at o (1213-6f9fd55cdf262f97.js:1:3303)`

**Comment by PeerRich** [comment]
@zomars or @emrysal  can you look into this?

**Comment by milospuac** [comment]
@MinhazI   Did you try reinstalling the Zoom app?

**Comment by MinhazI** [comment]
@milospuac I did not, I removed Google calendar. Lemme do that and keep you posted.

**Comment by MinhazI** [comment]
Hi, this issue keeps on coming back and doesn't get fixed unless I reinstall Zoom. Is there a way you guys can look into this please and let me know how I could continue to use Zoom on Cal.com without having to reinstall it every other day?

Thank you.

**Comment by MinhazI** [comment]
Hi @PeerRich and @milospuac, this issue persists almost every other day unless I reinstall Zoom. Is there a way we could have this fixed?

**Comment by PeerRich** [comment]
hey @minhazl upgrading to urgent and critical. not sure why this is happening, we'll investigate!

**Comment by zomars** [comment]
> Hi, this issue keeps on coming back and doesn't get fixed unless I reinstall Zoom.

[This is a known issue with zoom](https://devforum.zoom.us/t/users-refresh-token-keeps-expiring/41872/9). I'm afraid there's only so much we can do from our side.

The best answer we can give so far is: "Reinstall Zoom in Cal.com and logout from other devices until Zoom decides to support tokens for multiple devices"

**Comment by alannnc** [comment]
I'm currently investigating this!

**Comment by MinhazI** [comment]
> I'm currently investigating this!

Thank you @alannnc

**Comment by alannnc** [comment]
@MinhazI I made some updates on the DB and now it now should be working properly for you? Have you had any recent error in the last days?

**Comment by MinhazI** [comment]
Hi @alannnc, wonderful. I shall change the meeting to Zoom and test it out. I actually switched to Cal.com's video call till this issue was fixed. I shall revert back to Zoom and keep you posted.

Thank you for taking the time to look into this issue.

**Comment by MinhazI** [comment]
Hi @alannnc, I just checked, and the issue is still there. Am I supposed to reinstall Zoom on Cal.com? Please let me know if I should reinstall Zoom or if there are other steps that I should follow. Thank you.

**Comment by alannnc** [comment]
@MinhazI We have updated our code in production env with a fix for it and yes you should reinstall Zoom app and add location back to the event.

**Comment by MinhazI** [comment]
@alannnc Apologies for the delayed reply. I just tried it, and it works so far. I shall continue to test this for the next couple of days and then confirm if it works. Thank you for spending your time to fix it.

**Comment by alannnc** [comment]
@MinhazI No worries, glad I could help!
