### ISSUE TITLE
Incorrect .gitmodules

### ISSUE THREAD

**Issue by asm0dey** [calcom/cal.com#5351]
### Issue Summary

`.gitmodules` leads to inexistent repositories. The same behavior can be observed from the GitHub UI itself: navigation to `apps/api` fails, for example

### Steps to Reproduce

Clone the https://github.com/calcom/cal.com with submodules

Cloning fails with info about repos inaccessible

**Comment by JKetelaar** [comment]
Same issue here

**Comment by PeerRich** [comment]
@zomars

**Comment by JKetelaar** [comment]
It seems like you can pull the repo, ignore the submodules failing, and then run the build with `docker-compose build calcom` or `yarn dx`

**Comment by PeerRich** [comment]
yarn dx should fix this

**Comment by asm0dey** [comment]
Folks, I'm sorry, but it's still broken even if docker doesn't care about it at all… I mean, you still have this file in your repo, and on GitHub I still can't navigate to some subdirs (that should be projects theoretically). It's your project, so of course, you are the ones who decide what's wrong and what's not, but the behavior is not fixed.

**Comment by PeerRich** [comment]
@zomars will look into this, thank you for reopening @asm0dey

**Comment by zomars** [comment]
> Folks, I'm sorry, but it's still broken even if docker doesn't care about it at all… I mean, you still have this file in your repo, and on GitHub I still can't navigate to some subdirs (that should be projects theoretically). It's your project, so of course, you are the ones who decide what's wrong and what's not, but the behavior is not fixed.

Can you provide more context on the "incorrect behavior" you're experiencing?

Are the "submodule not found" errors blocking you in any way?

**Comment by asm0dey** [comment]
I don't think so. But if modules are not needed anymore - maybe they should
just be deleted?

This way recursive clone will work correctly and people won't need to dig
for this issue to understand that it doesn't need fixing

**Comment by zomars** [comment]
Modules are needed for our private repos. It shouldn't affect users at all. Hence my question. Those modules DO exist but are mainly used by ourselves and enterprise customers. Hope this clear things up.

**Comment by asm0dey** [comment]
Well, then instructions for docker build should be updated, I think.
Because they don't say it's a normal situation

**Comment by PeerRich** [comment]
> Well, then instructions for docker build should be updated, I think. Because they don't say it's a normal situation

yep, working on it with @krumware but also happy to accept PRs

**Comment by krumware** [comment]
Apologies, coming back from from out-of-office. Is this a docker question, or a question about the availability of the submodules? 

re docker, the instructions do mention in the cloning steps `Note: DO NOT use recursive submodule update, otherwise you will receive a git authentication error.`. Does that need to be rephrased to provide more context?
