### ISSUE TITLE
Meetings in Apple calendar are offset when calculating available time slots

### ISSUE THREAD

**Issue by belle-isle** [calcom/cal.com#5570]
Found a bug? Please fill out the sections below. 👍

The calendar I use is iCloud and I am located in continental Europe (CET). My Calendar is in this timezone on my device. I have confirmed on [icloud.com](http://icloud.com/) that it is the same there. When an event is scheduled via [cal.com](http://cal.com/), it is correctly scheduled at the right time. However, the events in my calendar that are checked for conflicts are not taken into account correctly. They are offset by 1 hour. It's as if an event set in the calendar outside of [cal.com](http://cal.com/) for 10:00 CET is in fact considered to be at 11:00 CET, thus defeating the purpose of the app, since double bookings are possible. Events which are schedules within [cal.com](http://cal.com/), however, are correctly taken into account.

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. I opened a new account
2. I added two Apple calendars, with preexisting meetings, and both set to Central European Time (CET)
3. I created an event type limited to 3 days in the future (for an event) and with an availability schedule for 10:00-19:00 every day
4. Then I went to the booking page
5. The unavailable time slots (due to a preexisting meeting) are offset by one hour on the booking page.
6. I can book a meeting during the preexisting meeting, resulting in a collision
7. That meeting appears correctly in the Apple calendar
8. That meeting also results in correct unavailable time slots

Thus, almost everything seems fine, apart from the fact that the preexisting events are incorrectly scheduled when calculating the available or unavailable time slots. The offset is 1 hour, which is the current time difference between my time zone and UTC - that could be the issue, perhaps.

### Technical details

OS : Mac OS and iOS (tried on 2 devices)
Browsers : Chrome 107 and Firefox 107 (tried both)
Calendar timezone : CET

**Comment by alishaz-polymath** [comment]
Hey @belle-isle this appears to be related to the daylight saving time issue. I am currently working on a fix for this and your patience is greatly appreciated in the mean time. Thank you for raising the ticket as well, much appreciated 🙏

**Comment by ready4sea** [comment]
Hi @alishaz-polymath , thanks for the reply and for working on a fix.
I tested again today and can you please confirm that the issue was fixed ?
It looks better now but I'd like to have confirmation before using it in production.
Thanks

**Comment by alishaz-polymath** [comment]
Hi @ready4sea 
This particular issue is not yet fixed, I'm afraid. The latest iCal bug fix was related to the timezone doubling when events are created on the native iCloud app as opposed to the web version. 
As for this particular issue, it's being worked on to identify a robust solution that you can trust on production. Sincere apologies for the delay 🙏

**Comment by chaoxu** [comment]
I think this is the same issue. 
If I copy something from this external calendar to my own ( https://icerm.brown.edu/calendar/?event=375&type=ical ) in apple calendar, Cal does not read the timezone. 

But if I copy it and change the time manually, there is no such problem.
