### ISSUE TITLE
Cannot use full time-slot prior to midnight

### ISSUE THREAD

**Issue by ahmedsadman** [calcom/cal.com#5587]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

For my work, I'm available from 10:30 PM to 1:30 AM. In the availability section, 11:46 PM to 11:59 PM gets totally wasted as there is no way to include that 15 min slot in my availability. Please refer to this image:
![xcxa](https://user-images.githubusercontent.com/11042267/202720919-6a42f300-9c57-439f-9de5-d0c1dcce6699.png)

As a result, I get the following slots (60 min event duration and 30 min slot interval):
![Screenshot 2022-11-18 195217](https://user-images.githubusercontent.com/11042267/202720588-cb2bbfc4-a660-49b9-a580-b57086abf399.png)

But if I could use that 15 mins time, I would get the following slots:
- 10:30 PM
- 11:00 PM
- 11:30 PM
- 12:00 PM
- 12:30 PM

### Steps to Reproduce

1. Try to make your availability span after midnight

**Comment by milospuac** [comment]
@emrysal Can you look into this?  From my understanding, 10:30 pm is the last slot someone can book for the day when you have 60-minute meetings. That meeting ends at 11:30 so there is essentially no space for another booking, that's fine. 

However, it's impossible to have a slot that starts at 11:00 pm that lasts until midnight. 11:45 is the limit of our availability. Is there a reason for those limitations?

**Comment by milospuac** [comment]
@emrysal

**Comment by 12ian34** [comment]
I believe this issue has been resolved with https://github.com/calcom/cal.com/pull/6137 (just not released yet)

**Comment by ahmedsadman** [comment]
> I believe this issue has been resolved with #6137 (just not released yet)

It's one step towards the fix but doesn't solve the whole issue. Added a new comment on that PR with details.

**Comment by PeerRich** [comment]
closing because we have a new ticket: https://github.com/calcom/cal.com/issues/6323
