### ISSUE TITLE
Calendar availability is not correct when an "all-day" event is used in iCal

### ISSUE THREAD

**Issue by jsolly** [calcom/cal.com#6292]
Found a bug? Please fill out the sections below. 👍

## Issue Summary
When I add an 'all-day' event in a connected iCal calendar, I still see availability on that day.

## Steps to Reproduce
1 - Connect an iCalendar and use it to check for conflicts
2 - Add an 'all-day' event on the iCalendar
3 - Check cal.com availability on the day that the all-day event is occurring
You will still see availability on this day.

### Example
I am running into this issue on MacOS ical. Today I have an all-all day event, but cal.com is showing me as available after 4PM
## cal.com (Screenshot taken at 10:30AM)
![image](https://user-images.githubusercontent.com/9572232/210853807-32bc2c82-80ac-438c-b248-30d6d03e82d5.png)

### ('🥟 # 2 work' is an all-day event today on the work/school calendar) 
![image](https://user-images.githubusercontent.com/9572232/210854140-8daa525e-66a3-497a-8a87-fb2a705cb3a4.png)

## Availability
![image](https://user-images.githubusercontent.com/9572232/210853592-f59ee585-c804-4229-8c92-08ad420f57d4.png)

## Check for Conflicts
![image](https://user-images.githubusercontent.com/9572232/210854360-9eeb6874-ee0b-4976-9ec7-d7d2c6cfae00.png)

What is strange is that it seems to block all other time slots. It's just 4PM onward that stays available.

## Technical details
Browser: Brave [Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (arm64)](https://brave.com/latest/)

Happy to provide bird eats bug report if needed.

## Related issues
https://github.com/calcom/cal.com/issues/2240 (This was a user error with Google Calendar)

**Comment by jsolly** [comment]
This might have worked itself out. I am now seeing 'All booked today' on days with an 'all-day' event in iCal. Feel free to close.

**Comment by jsolly** [comment]
Update. It's not working for me. Any ideas what could be going wrong? Here is a video of me reproducing the issue
https://app.screencast.com/UY6Wo3o532tGP

**Comment by PeerRich** [comment]
@alishaz-polymath can you look into this?

**Comment by NicolaiSchmid** [comment]
It seems to be blocking fine, in my case, if the all-day event spans multiple days (using the hosted version of cal.com)

**Comment by jsolly** [comment]
I guess IDK what to say. Cal.com is completely unusable for me because it does not detect events from my iCAL:
![image](https://user-images.githubusercontent.com/9572232/216908017-f5e36d49-4982-4c03-8f6e-f44a82a0b71d.png)
![image](https://user-images.githubusercontent.com/9572232/216907937-0ee10921-8b53-44f2-81f0-ba332756c338.png)

**Comment by alishaz-polymath** [comment]
Hey @jsolly 
Apologies for the issue you're facing. Let me take a look at this today and report back with the findings 🙏

**Comment by jsolly** [comment]
Happy to jump on a video call. Just DM me and I can send a schedule link.

I worked in QA for 4 years and am now a developer. I am sure we could figure it out.

**Comment by jsolly** [comment]
Hey. Just pinging this again since it's been 2 weeks. @alishaz-polymath and I were able to reproduce it on my account together.

Happy to provide any additional diagnostics and/or another screen share. This is a show-stopper for me = /

**Comment by solace** [comment]
Aloha!

To add, I created an all-day busy event in iCal on macos but for a Google calendar. The Google Calendar web interface shows the all-day busy event. It reflects on my phone as well. Calendly, which is still connected correctly shows that whole day as unavailable, but cal.com still shows availability on that day.

Let me know what you need from me as well. I'm a dev as well so if you need to set debug on my account(s) to increase visibility for you, have at it.

**Comment by jsolly** [comment]
I tried this out again with the new release.

The Calendar troubleshooter is showing me busy at the right times, but I now have no availability at all in any month (even for a 15 min meeting)
![image](https://user-images.githubusercontent.com/9572232/232911329-8e140bb7-f960-4386-96b1-483b3c1835e2.png)

**Comment by alishaz-polymath** [comment]
Hey @jsolly 
Let’s have another session and try again to sort this out
Cal.com/ali/debugging

**Comment by njyo** [comment]
Hi, so for me this issue remains with holiday calendar subscriptions. For example, May 1 is Labour Day (at least in many parts of the world) and the Google Holiday calendar indicates that correctly.

![2023-04-28 at 12 55](https://user-images.githubusercontent.com/988408/235057786-f68b60c6-1674-4c3e-874b-e9f8e408bd0d.png)

However, there is no way to set those days as "Busy".

![2023-04-28 at 12 57](https://user-images.githubusercontent.com/988408/235057876-f3ea36bd-a4f4-443b-8b5e-e038b8f8b2b7.png)

Which is why, my Cal allows people to schedule on that day…

![2023-04-28 at 12 58](https://user-images.githubusercontent.com/988408/235058054-2ecbcb07-0c61-4024-97db-a0c096d2b294.png)

To me, there would be two possible solutions:

1. Allow in the conflict checker to toggle `Block out days with full-day events` on
2. Integrate some public holiday service (Google Calendars, date.nager.at, etc.) and allow pulling in one or more public holiday calendars to block out days.

![2023-04-28 at 12 59](https://user-images.githubusercontent.com/988408/235058526-5bb05cd3-39f6-423d-a713-c060c2554b1c.png)

Thanks!

**Comment by alishaz-polymath** [comment]
Hey @Rustymage I'm currently exploring this bug. All day events don't carry timezone according to the iCalendar 2.0 standard (RFC) and so we need the timezone information from your cal.com account for this. We're currently figuring out the best way to do this that ensures minimum performance impact because of this. This should be sorted very soon!

**Comment by Rustymage** [comment]
All day bookings on iOS are respected by cal.com.

**Comment by njyo** [comment]
Thanks @Rustymage.

Sadly, holiday calendar subscriptions are not created on any device but just subscriptions and—as said—do not block out time on my cal.com. :$

**Comment by Rustymage** [comment]
> Thanks @Rustymage.
> 
> 
> 
> Sadly, holiday calendar subscriptions are not created on any device but just subscriptions and—as said—do not block out time on my cal.com. :$

Fair enough. I've found some of my holiday calendars work and some don't. Not sure on the reasons :/ 

I've actually tried the Fantastical Openings offering and they too have the same all-day issue.

**Comment by njyo** [comment]
Some working, some not is even more annoying. :$
At least for now adding and removing the holiday calendar did not work for me. :(

Thanks for the tip though.

**Comment by Rustymage** [comment]
Looks like iCloud calendar may be the issue with it's missing free/busy sections.

https://forums.macrumors.com/threads/free-busy-other-status-options-missing-in-calendar-app.2369504/

**Comment by njyo** [comment]
My calendars are coming in from Google though (see screenshots above).

**Comment by Rustymage** [comment]
> Looks like iCloud calendar may be the issue with it's missing free/busy sections.
> 
> https://forums.macrumors.com/threads/free-busy-other-status-options-missing-in-calendar-app.2369504/

If I use Fantastical to create the all day event and select busy, cal.com respects that. If I make it free, cal.com says I'm free.

**Comment by alishaz-polymath** [comment]
Just FYI, the latest release (https://github.com/calcom/cal.com/releases/tag/v2.8.13) sorts this one out 🎉 
@jsolly Please give it a go and let me know the results🙏

**Comment by njyo** [comment]
Doesn't seem to work for me still… looking at June 2nd, a holiday here:

![2023-05-12 at 10 25](https://github.com/calcom/cal.com/assets/988408/c44d131e-b530-4529-ba70-8e4558637c5d)

![2023-05-12 at 10 26](https://github.com/calcom/cal.com/assets/988408/53f730df-37c8-448a-be42-cec1a0b2263b)

😕

**Comment by alishaz-polymath** [comment]
Can you confirm you are have the same timezone set in your cal.com profile as well, at cal.com/settings/my-account/general?

**Comment by alishaz-polymath** [comment]
> Doesn't seem to work for me still… looking at June 2nd, a holiday here:
> 
> ![2023-05-12 at 10 25](https://user-images.githubusercontent.com/988408/237853665-c44d131e-b530-4529-ba70-8e4558637c5d.png)
> 
> ![2023-05-12 at 10 26](https://user-images.githubusercontent.com/988408/237853703-53f730df-37c8-448a-be42-cec1a0b2263b.png)
> 
> 😕

Oh wait, it should have the availability as busy to work. Holidays don't have busy availability by default.

**Comment by njyo** [comment]
Hi @alishaz-polymath, thanks, yes, both time zones are the same (Asia/Kuala_Lumpur).

Sorry, I'm not sure what your last statement means… [what I've raised before is that holidays should be possible to be marked as unavailable by default](https://github.com/calcom/cal.com/issues/6292#issuecomment-1526994473). As mentioned before, I would see two possible solutions for this:

1. I can select that all events on a given calendar should be considered as busy (irrespective of the calendar and event type type)
2. The conflict calendar selection should let me add Holiday calendar subscriptions…

**Comment by jsolly** [comment]
Hi all! This is working perfectly for me. Cal.com respects all-day events made in an Apple calendar as well as events that are not all day. Thanks for the fix!

I am comfortable with this issue being closed @alishaz-polymath

**Comment by njyo** [comment]
> > Hi @alishaz-polymath, thanks, yes, both time zones are the same (Asia/Kuala_Lumpur).
> > Sorry, I'm not sure what your last statement means… [what I've raised before is that holidays should be possible to be marked as unavailable by default](https://github.com/calcom/cal.com/issues/6292#issuecomment-1526994473). As mentioned before, I would see two possible solutions for this:
> > 
> > 1. I can select that all events on a given calendar should be considered as busy (irrespective of the calendar and event type type)
> > 2. The conflict calendar selection should let me add Holiday calendar subscriptions…
> 
> I see. What you're mentioning is a feature request more than an issue to be honest, as it is an additional functionality request and not a bug/issue. Could you please raise a new feature request with the same? 🙏

Done here #8918. Thanks!

**Comment by EduNetEurope** [comment]
For us, the problem still exists with multiple-day events that start on, let's say, 4pm on day 1 and go to 10am on day 3.

**Comment by gatto** [comment]
This is still an issue for me today with iCloud calendar, appointments created with macOS Calendar. Latest macOS 14.5.
I'm happy to help debug this if anyone from the dev team wants to look into it.
Makes the service fairly unusable for me unfortunately.

**Comment by natew** [comment]
Actually my issue is that I'd like at least the option to not have it block.

For example - I am traveling and put the hotel information for the next two months as all-day events which is very convenient. But iCal doesn't seem to have a "busy" toggle as far as I can see. I'd not like those to block, but just those events.

**Comment by natew** [comment]
For now I've just made a new calendar category and unsynced that.

**Comment by regoawt** [comment]
Still an issue creating all-day events through MacOS 15.5 Calendar
