### ISSUE TITLE
[CAL-816] event type description: line break not applied on booking page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6535]
![CleanShot 2023-01-17 at 22.56.36@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/72ba7a30-13b9-4821-af54-d217ab308a7c/bfad3ec3-8d78-4102-9b6d-d249c0a25616)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-816](https://linear.app/calcom/issue/CAL-816/event-type-description-line-break-not-applied-on-booking-page)</sub>

**Comment by G3root** [comment]
@PeerRich  can't seems to reproduce this. https://cal.com/nafees-nazik-f5xuwp/test-event

**Comment by PeerRich** [comment]
i think this has been fixed by @CarinaWolli recently

**Comment by CarinaWolli** [comment]
I didn't work on that yet. So I think line breaks are still not working. But this will be added when implementing the editor component for description (#5764)
