### ISSUE TITLE
[CAL-1044] remove markdown from description and convert to html for social preview

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7057]
![9B01F015-425C-4BD7-9984-F93BFB1F4052.jpeg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b1215104-729e-4fc1-a07e-219cda489bfb/e617f2ea-c2b6-4ee3-8caf-5921c0e969dd)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1044](https://linear.app/calcom/issue/CAL-1044/remove-markdown-from-description-and-convert-to-html-for-social)</sub>

**Comment by saideepesh000** [comment]
hey @PeerRich , please assign this to me, can u also give some more details on this?

**Comment by sean-brydon** [comment]
> hey @PeerRich , please assign this to me, can u also give some more details on this?

Hey @saideepesh000 when you test our social preview it brings back the users bio - However the string that is brought back has markdown inside of it - We either need to strip the markdown from this bio when its previewed on OG images or convert it to the html equivalent 

The above would become 
**Software Developer**
CS at

**Comment by PeerRich** [comment]
hey @saideepesh000 assigned you! thank you for offering the help

**Comment by herropaul** [comment]
Hey, was curious on this issue but is the link preview bug only affecting on those socials? (fb, twitter, linkedin, pinterest)?

**Comment by saideepesh000** [comment]
hey @PeerRich , how do i get to this page ?

**Comment by saideepesh000** [comment]
> hey @PeerRich , how do i get to this page ?

hey @PeerRich , wanted to get the update here

**Comment by PeerRich** [comment]
its not a page, it's the og-image (social preview) but I think it has been fixed by @CarinaWolli

**Comment by CarinaWolli** [comment]
Should have been fixe here: https://github.com/calcom/cal.com/pull/7474 but I still see the issue. @G3root could you take a look at that again?
