### ISSUE TITLE
[CAL-1179] [CAL-1098] 50-minute slot not calculated correctly

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7167]
Last slot of the day is 40 minutes and is causing the "No available users found"

This user has availability until 18:00 on that day.

17:20 is not supposed to be there

![Screenshot 2023-02-17 at 09.12.15.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/904dec5e-a33d-4788-93f9-020bbd1a2f15/e4216281-ffd8-461b-a6d4-0d8e6f85471c)

![Screenshot 2023-02-17 at 09.13.46.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c14519a2-1222-4e31-a3c3-c162e2d47a94/7a506d9d-62c8-4aad-a5fa-9d476566a583)

![Screenshot 2023-02-17 at 09.28.18.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/043afb7b-2f00-4912-b181-f0352bffa27b/21413d66-485c-44e8-96f4-2d650a613b4f)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1098](https://linear.app/calcom/issue/CAL-1098/50-minute-slot-not-calculated-correctly)</sub>

<sub>[CAL-1179](https://linear.app/calcom/issue/CAL-1179/[cal-1098]-50-minute-slot-not-calculated-correctly)</sub>

**Comment by kanarian** [comment]
I think it might be because of the `+15` of the [packages/lib/slots.ts](https://github.com/calcom/cal.com/blob/main/packages/lib/slots.ts#L84) file:

```if (slotStart < item.startTime || slotStart > item.endTime + 15 - eventLength) ```

I reproduced this bug locally and saw that deleting the `+15` or changing it to a value strictly less than 10 made it work. Not sure why the `+15` is needed.

**Comment by harshsinghatz** [comment]
@kanarian yeah that seems to be the issue but dk what was the product req for this logic

**Comment by PeerRich** [comment]
cc @emrysal

**Comment by tomml** [comment]
I am facing the same error message. See my bookings: https://cal.com/mobile-massage-rgb/25 There, the appointment for 3:55pm (timezone is europe/amsterdam as I am from germany) should be bookable, but if I understand correctly it does not fit my availability. The availability time slot can only be set by 15min slots. Mine is set to 1pm till 4:15pm. The appointment time by the other hand can be an exact 1min slot. 25minutes in my case. I tried to make my availability till 4:30pm, but then there appears another appointment starting at 4:20pm, which also does not fit the availability schedule. With this time settings always the last appointment slot is not bookable by my clients facing the error message OP posted.

**Comment by tomml** [comment]
Any chance to get this issue fixed soon?

**Comment by roae** [comment]
Hey @tomml can you try again, we deployed a new release today

**Comment by tomml** [comment]
@roae tried it. But still the same issue.
I guess it is because the appointment slot (25mins) does not fit the availability. As mention previously this results in always the last appointment is not being able to be booked and results in the error message OP posted.
To fix this presumably, the availability slot shall be set by 1 minute rather than 15 min slots. This allows to exactly align with the appointment slots. What do you think?

**Comment by tomml** [comment]
Fixed for me @roae @PeerRich

**Comment by emrysal** [comment]
Closing to reflect status, thank you @roae
