### ISSUE TITLE
Attendee receiving a double calendar invite, and rescheduling does not remove one

### ISSUE THREAD

**Issue by jacobzukerman** [calcom/cal.com#7735]
We are testing the latest Cal version, and we are getting two Calendar invites automatically added to Google Calendar. One invite has both the Host and Attendee, and the other is just an invite with the Attendee on it. This is happening on our self-hosted experience and on app.cal.com. Our current self-hosted production version is v.2.5.5-sh-ce and this issue does not happen. 

<img width="829" alt="Screen Shot 2023-03-14 at 1 42 27 PM" src="https://user-images.githubusercontent.com/37521186/225131639-7955ec9a-4455-4266-aeb9-531f0e383a0d.png">

When rescheduling, one invite stays behind, and then another two get generated. This with lead to a ton of user confusion. 

<img width="521" alt="Screen Shot 2023-03-14 at 1 33 49 PM" src="https://user-images.githubusercontent.com/37521186/225131719-ccadeab6-6d02-45cd-bf1c-7b11be7f34cc.png">

**Comment by jacobzukerman** [comment]
Seems to be related to https://github.com/calcom/cal.com/issues/7703

We are getting this now consistently, I never had this happen before during our QA process.

**Comment by jacobzukerman** [comment]
Also, please note that there is a formatting issue with the cancellation reason, and when rescheduling, it seems that the the Cal Video location gets lost on the new invite. 

<img width="431" alt="Screen Shot 2023-03-14 at 2 00 37 PM" src="https://user-images.githubusercontent.com/37521186/225135265-3515f6ca-d82c-40c8-b784-c426758b45a0.png">

**Comment by PeerRich** [comment]
can you try again? I think this was fixed in the last update 2.7.2

**Comment by piec** [comment]
Hi here is a way to reproduce it on https://cal.com
* Both of my users are on a google account
* The google calendar integration must be enabled, google meet is off 
* The attendee creates a booking on the host's page
* The attendee receives an email like
> Your event has been scheduled
> You and any other attendees have been emailed with this information.

An event is created in his calendar and starts with the same text.

* The host receives an email like:
> A new event has been scheduled.
> 
> What
> 
> Meeting between X and Y

An event is created in his calendar and starts with "What:"

* Now only if the google calendar integration is enabled the attendee also receive this second event.
I assume that it's due to the fact that google sends an invitation to all emails invited to the event.
I think that it should be possible to prevent google from sending invitations?
See https://developers.google.com/calendar/api/v3/reference/events/insert#sendUpdates ?

Hope this helps,
Cheers,
Pierre

**Comment by rashabarbar** [comment]
This issue persists. I reported it on May 15, 2024 and Support suggested it was Ethereum-related, which doesn’t seem likely given the context.

![Image](https://github.com/user-attachments/assets/9c8b05c3-43a8-43b4-a511-808bf8d05297)
