### ISSUE TITLE
Recurring meeting bookings fail if events occur beyond set limits

### ISSUE THREAD

**Issue by ChipWolf** [calcom/cal.com#7816]
### Issue Summary

If recurring events are enabled for an event type, on the booking page, the booking errors if the number of events runs over the set limited future bookings threshold.

![](https://i.imgur.com/yb1xqO0.gif)

### Steps to Reproduce

1. Limit future bookings to a fixed number of days
2. Enable recurring events to allow booking more slots than the limit you set
3. Attempt to book the event type with a higher number of slots than shown availability

**Comment by G3root** [comment]
@ChipWolf is this still happening ? can't  reproduce after `v2.7.2`

**Comment by ChipWolf** [comment]
@G3root @PeerRich still an issue, replicate here: https://cal.com/chip/10

**Comment by PeerRich** [comment]
@G3root wanna look again into this?

**Comment by G3root** [comment]
> @G3root wanna look again into this?

I'll look into it

**Comment by PeerRich** [comment]
@Udit-takkar can you take this over?

**Comment by PeerRich** [comment]
there is a chance this has been fixed

**Comment by nicktrn** [comment]
Still happening

[recur-limit.webm](https://github.com/calcom/cal.com/assets/55853254/593be4d2-3939-451a-83f9-2f6b9a632c15)
